import React, { Component } from 'react'

export default class FormatIgeData extends Component {
  render() {
    return (
      <div>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
        <p>sfsdfsdf</p>
      </div>
    )
  }
}
